### ISSUE TITLE
Dont work for my url.

### ISSUE THREAD

**Issue by BibaBoba2Dalbaeba** [aioqzone/pychaosvm#4]
Url: https://cdn.midasbuy.com/js/x-midas/kEc9hjFh5DQJbz_iPEWrfFxadMVk4PbLDS-5P8jE73pfdUuDwNGKNVZjdEztcHdofAVaHXo6zRGXgLwuvsK_afAEj6w_mKyiUmq-7AesIRU~.js?max_age=31536000
KeyError: 'expression'

**Comment by JamzumSum** [comment]
This package is designed as a component of [aioqzone](https://github.com/aioqzone/aioqzone), and it is not guaranteed to work on any other URLs.

> KeyError: 'expression'

However, you are welcomed to provide more info about this. I think all `chaosvm`s have similar logics.
