### ISSUE TITLE
can not support appid: 1600000770

### ISSUE THREAD

**Issue by My-Responsitories** [aioqzone/pychaosvm#5]
verify post data:
```python
collect = str(sess.tdc.getData(None, True))

ans = {
    'elem_id': 1,
    'type': sess.piece_sprite.move_cfg.data_type[0],
    'data': "{0},{1}".format(*sess.jig_ans),
}
data = {
    "collect": collect,
    "tlg": len(collect),
    "eks": str(sess.tdc.getInfo()["info"]).strip("'"),
    "sess": sess.prehandle.sess,
    "ans": f'[{ujson.dumps(ans)}]',
    "pow_answer": hex_add(sess.conf.common.pow_cfg.prefix, sess.pow_ans),
    "pow_calc_time": sess.duration,
}
```
Other codes are consistent with https://github.com/aioqzone/aioqzone/blob/beta/src/qqqr/up/captcha/__init__.py
return data:
```
code=12 verifycode='' ticket='' errMessage='' sess='******'
```
`code=12` is the same as what I returned using selenium. It seems to be detected

But I type  `appid=549000912`, it runs successfully

**Comment by JamzumSum** [comment]
> `code=12` is the same as what I returned using selenium. It seems to be detected
> 
> But I type `appid=549000912`, it runs successfully


From my experience, the _verify_ process does not test the `collect` field. In another word, if we got a wrong `collect` result (which is generated by `pychaosvm`), the _verify_ process may still return a success code.

The _verify_ process may test other fields, such as `ans` in the snippet above. Maybe you are missing some fields, or posting a wrong value. This could explain why `appid=549000912` passed but others couldn't.

Lastly,`pychaosvm` is designed to work only on Qzone service. It is okay to look up it for reference, but it is not guaranteed to work on other services.
