### ISSUE TITLE
运行时间大概需要3s，能否指导下该优化哪块，可以提高下识别速度

### ISSUE THREAD

**Issue by iptag** [aioqzone/pychaosvm#57]
感谢大佬~

**Comment by JamzumSum** [comment]
> 这个项目本来只是服务于特定输入的。泛用的话，它一是不完备，补环境不是面面俱到；二是不准确，很多操作只是有条件的正确。在这种情况下，不敢奢谈性能优化。

具体到这个问题，我也不知道该怎么优化，毕竟我不会算卦。

对于一套给定的输入来说，想要优化执行时间大概要从两个方面着手。第一，用随便什么profiling工具出一份报告；第二，了解你输入的虚拟机在做什么，并和profiling报告比对。

当你确切地发现一个操作是异常耗时的，并提供相应的输入结果等，这时我才能提供优化建议。

**Comment by iptag** [comment]
非常感谢，经过好多次运行后发现大佬的代码实际运行时间大概在0.3秒左右，但是要完成一次完整的滑块识别还有一些网络请求以及其他参数的计算，这些过程有时不能很好的控制他们的执行时间，再次感谢大佬的代码！
