### ISSUE TITLE
新版的vm不能用了

### ISSUE THREAD

**Issue by keatonLiu** [aioqzone/pychaosvm#58]
新版vm地址，改了op_def_list和一些小地方：https://turing.captcha.qcloud.com/tdc.js?app_data=7256590633187913728&t=274437327?t=1730106028

**Comment by JamzumSum** [comment]
是否有必要支持多个版本的vm呢？之前是手动生成了当时那个版本的语法树md5然后写死到`OP_FEATS`里了

**Comment by keatonLiu** [comment]
可以extend一下，改动应该也不大
